apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarea-api
  namespace: tarea-aplicacion
spec:
  selector:
    matchLabels:
      aplicacion: tarea-api
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: tarea-api
    spec:
      containers:
        - name: api-tarea
          image: mava13/imagenlaravel
          ports:
            - containerPort: 8001
