apiVersion: v1
kind: Service
metadata:
  name: tarea-api
  namespace: tarea-aplicacion
spec:
  type: NodePort
  selector:
    aplicacion: tarea-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30300
